# Usamos la imagen oficial y ultima de Nginx
FROM nginx:latest

# Instalamos las dependencias de Git en el contenedor
RUN apt-get update && apt-get install -y git

# Clonamos el repositorio de GitHub en el contenedor
RUN rm -rf /usr/share/nginx/html && git clone https://github.com/alexlpda1420/Portfolio.git /usr/share/nginx/html

# Copiamos el archivo default.conf personalizado al directorio de configuración de NGINX
COPY default.conf /etc/nginx/conf.d/default.conf

# Exponemos el puerto 80
EXPOSE 80
# Ejecutamos el cmd para Nginx
CMD ["nginx", "-g", "daemon off;"]
