# Usamos la imagen oficial de Prometheus
FROM prom/prometheus:latest

# Copiamos el archivo de configuracion de Prometheus
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Exponemos el puerto 9090
EXPOSE 9090

# Ejecutamos el cmd de Prometheus
CMD ["--config.file=/etc/prometheus/prometheus.yml"]
