global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'web'
    static_configs:
      - targets: ['web:80']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
      
  - job_name: 'web-1'
    static_configs:
      - targets: ['web:8080']
      
  - job_name: "Nginx"
    metrics_path: /metrics
    static_configs:
      - targets: ['nginxexporter:9113']